# Generated by Django 6.0.3 on 2026-03-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['date', 'start_time'], 'verbose_name_plural': 'Workshops'},
        ),
        migrations.AlterField(
            model_name='workshop',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
