# Generated by Django 6.0.3 on 2026-03-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('workshops', '0003_workshopcategory_workshop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='workshops', to='core.tag'),
        ),
    ]
