# Generated by Django 6.0.3 on 2026-03-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0003_workshopcategory_workshop_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage or promotional sections')),
                ('is_public', models.BooleanField(default=True, help_text='Visible to all users if True, otherwise only staff can see')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='workshops.workshop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
